-- MySQL Script generated by MySQL Workbench
-- Tue Jan 19 10:35:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Estaciones
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Estaciones` ;

-- -----------------------------------------------------
-- Schema Estaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Estaciones` ;
SHOW WARNINGS;
USE `Estaciones` ;

-- -----------------------------------------------------
-- Table `Estaciones`.`estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estaciones`.`estacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Estaciones`.`estacion` (
  `idestacion` INT NOT NULL AUTO_INCREMENT,
  `nombreestacion` VARCHAR(45) NULL,
  `telefonoestacion` VARCHAR(45) NULL,
  `direccionestacion` VARCHAR(45) NULL,
  `latitud` DOUBLE NULL,
  `longitud` DOUBLE NULL,
  PRIMARY KEY (`idestacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Estaciones`.`estacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `Estaciones`;
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (01, 'Estacion el Prado', '2242612', 'Carrera 20 # 25 41', 4.087963600743078, -76.2016288673446);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (02, 'Los profesionales', NULL, 'Calle 34 # 31 77', 4.078289952262172, -76.19626833661565);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (03, 'EDS El terminal', '2249998', 'Carrera 20 # 27A 28', 4.0858660962889415, -76.20184074802744);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (04, 'Terpel Tulua ', '3183162628', 'Via RioFrio', 4.088578923875464, -76.21580742314305);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (05, 'EDS Texaco 26', '2247249', 'Calle 27 # 30 01', 4.084684161056595, -76.19467417127404);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (06, 'Gazel', '2242707', 'Carrera 27A # 40 39', 4.070921145345564, -76.19732322987656);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (07, 'Estacion de servicio Texaco', NULL, 'Calle 32 Carrera 40 Esquina', 4.078295545776264, -76.1890323377809);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (08, 'Terpel Tulua', NULL, NULL, 4.085371307430105, -76.18630419002551);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (09, 'EDS Terpel Entre Rios', NULL, 'Carrera 30 # 163', 4.092596434077139, -76.19015969231661);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (10, 'Estacion Gas Natural', NULL, NULL, 4.071645046223833, -76.19324558553612);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (11, 'Terminal Tulua', NULL, NULL, 4.0857529276216065, -76.20217507188164);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (12, 'Estacion de Servicio La Ribera', '2248263', 'Calle 25 Carrera 40 Esquina', 4.085628145163381, -76.18630419002551);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (13, 'Estacion de Servicio Biomax San Antonio', '2333344', NULL, 4.090434875665899, -76.19200990022652);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (14, 'Estacion de Servicio Terpel KM0 Tulua Bugalagrande', NULL, NULL, 4.164914571792741, -76.17633397065552);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (15, 'Esso El Pedregal', NULL, 'Carrera 27A # 42 2', 4.0754915620687004, -76.19738009235839);
INSERT INTO `Estaciones`.`estacion` (`idestacion`, `nombreestacion`, `telefonoestacion`, `direccionestacion`, `latitud`, `longitud`) VALUES (16, 'Terpel Tulua', NULL, NULL, 4.061799532275269, -76.19956703104639);

COMMIT;

